
import Layout from "@/components/layout";
import Head from 'next/head'

export default function AboutMe(){
    return (
        <Layout>
        <Head>
          <title>개발자 백미정의 포트폴리오</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 class="text-center text-green-700 text-4xl font-bold ">
            GeeksforGeeks
        </h1> 
        <div className="grid grid-cols-3 gap-2 place-items-center m-4">
            <div>dddd</div>
            <div>dddd</div>
            <div>dddd</div>
            <div>dddd</div>
            <div>dddd</div>
            <div>dddd</div>

        </div>
        </Layout>
    )
}