import Head from 'next/head'
export default function Call(){
    return(
        <>
            <Head>
            <title>포트폴리오</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/heart .ico" />
            </Head>        
            <h1>연락하기</h1>
        </>
    );
}