
import Layout from "@/components/layout";
import Head from 'next/head'
import { Roboto } from "@next/font/google";

export default function AboutMe(){
    return (
        <Layout>
        <Head>
          <title>개발자 백미정의 포트폴리오</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/heart .ico" />
        </Head>
        <div className=" mx-10 mt-3 ">
            <h1 class="text-center text-black text-5xl font-bold p-5">
                skills
            </h1> 
            <div className="grid grid-cols-2 gap-4 place-items-center m-5 ">
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                        <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">Tools</h2>
                        <div className="flex w-auto justify-around">
                            <img className="max-h-[50px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/3053/PNG/512/microsoft_visual_studio_code_alt_macos_bigsur_icon_189955.png" />
                            <img className="max-h-[50px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/1381/PNG/512/eclipse_94656.png" />
                            <img className="max-h-[50px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/3053/PNG/512/intellij_macos_bigsur_icon_190061.png" />
                        </div>
                    </div>
                    <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">Version Control</h2>
                    <div className="flex w-auto justify-around">
                        <img className="max-h-[70px] md:max-h-[150px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/git_original_wordmark_logo_icon_146510.png" />
                        <img className="max-h-[70px] md:max-h-[150px] " src="https://cdn.icon-icons.com/icons2/2406/PNG/512/github_git_icon_145985.png" />
                    </div>
                </div>

            </div>
            <div className="grid grid-cols-3 gap-4 place-items-center m-5 ">
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">FrontEnd</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_html_icon_130541.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_css_icon_130661.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_js_official_icon_130509.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/react_original_wordmark_logo_icon_146375.png" />
                        {/* <img className="max-h-[70px] md:max-h-[130px] " src="https://images.viblo.asia/aec9657d-51c9-4d60-acc3-b784680ff410.png" /> */}
                    </div>
                </div>
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">BackEnd</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/java_original_wordmark_logo_icon_146459.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://cdn-icons-png.flaticon.com/512/5098/5098178.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://velog.velcdn.com/images%2Fjogiyo%2Fpost%2F1c272be7-0161-48fe-b3c8-2d989671849d%2Fspringboot.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/nodejs_original_wordmark_logo_icon_146412.png" />
                    </div>
                </div>
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">DataBase</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/oracle_original_logo_icon_146401.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://cdn.icon-icons.com/icons2/2415/PNG/512/mysql_original_wordmark_logo_icon_146417.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="https://media.amazonwebservices.com/blog/2015/mariadb_seal_shaded_browntext_alt_1.png" />
                    </div>
                </div>
            </div>

        </div>
        </Layout>
    )
}