
import Layout from "@/components/layout";
import Head from 'next/head'
import { Roboto } from "@next/font/google";

export default function AboutMe(){
    return (
        <Layout>
        <Head>
          <title>개발자 백미정의 포트폴리오</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/heart .ico" />
        </Head>
        <div className=" mx-10 mt-3 ">
            <h1 class="text-center text-black text-5xl font-bold p-5">
                skills
            </h1> 
            <div className="grid grid-cols-2 gap-4 place-items-center m-5 ">
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                        <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">Tools</h2>
                        <div className="flex w-auto justify-around">
                            <img className="max-h-[50px] md:max-h-[130px] " src="visual_studio_code.png" alt="visual" />
                            <img className="max-h-[50px] md:max-h-[130px] " src="eclipse.png" />
                            <img className="max-h-[50px] md:max-h-[130px] " src="intellij.png" />
                        </div>
                    </div>
                    <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">Version Control</h2>
                    <div className="flex w-auto justify-around">
                        <img className="max-h-[70px] md:max-h-[150px] " src="git.png" />
                        <img className="max-h-[70px] md:max-h-[150px] " src="github.png" />
                    </div>
                </div>

            </div>
            <div className="grid grid-cols-3 gap-4 place-items-center m-5 ">
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">FrontEnd</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[130px] " src="html.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="css.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="js.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="react.png" />
                        <img className="max-h-[70px] md:max-h-[130px] " src="https://images.viblo.asia/aec9657d-51c9-4d60-acc3-b784680ff410.png" />
                    </div>
                </div>
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">BackEnd</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[140px] " src="java.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="jsp.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="springboot.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="nodejs.png" />
                    </div>
                </div>
                <div className="mx-10 mb-4 w-full h-full rounded-lg bg-lime-200">
                    <h2 class="text-center text-black bg-amber-300 text-xl md:text-2xl font-bold m-3 ">DataBase</h2>
                    <div className="grid sm:grid-cols-2 w-auto place-items-center">
                        <img className="max-h-[70px] md:max-h-[140px] " src="oracle.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="mysql.png" />
                        <img className="max-h-[70px] md:max-h-[140px] " src="mariadb.png" />
                    </div>
                </div>
            </div>

        </div>
        </Layout>
    )
}